/amr/mqtt_robot_plugin:
  ros__parameters:
    broker:
      host: "192.168.61.35"
      port: 1883
      client_id: "amr_mqtt_robot_plugin"
      keep_alive_sec: 20
      clean_session: true
      username: ""
      password: ""
    mqtt:
      root: "amr/robot/turtlebot3"
      qos:
        telemetry: 0
        command: 0
      topics:
        telemetry:
          map: "amr/robot/turtlebot3/telemetry/map"
          scan: "amr/robot/turtlebot3/telemetry/scan"
          odom: "amr/robot/turtlebot3/telemetry/odom"
          imu: "amr/robot/turtlebot3/telemetry/imu"
          tf: "amr/robot/turtlebot3/telemetry/tf"
          tf_static: "amr/robot/turtlebot3/telemetry/tf_static"
          joint_states: "amr/robot/turtlebot3/telemetry/joint_states"
        command:
          cmd_vel: "amr/robot/turtlebot3/command/cmd_vel"
    ros:
      topics:
        map: "/amr/map/data"
        scan: "/scan"
        odom: "/odom"
        imu: "/imu"
        tf: "/tf"
        tf_static: "/tf_static"
        joint_states: "/joint_states"
        cmd_vel: "/cmd_vel"
