<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>amr_navigation</name>
  <version>0.1.0</version>
  <description>Entry metapackage for the ROS AMR navigation stack.</description>
  <maintainer email="reidlo4215@gmail.com">reidlo</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>amr_msgs</exec_depend>
  <exec_depend>amr_map_server</exec_depend>
  <exec_depend>amr_localization</exec_depend>
  <exec_depend>amr_global_planner</exec_depend>
  <exec_depend>amr_local_planner</exec_depend>
  <exec_depend>amr_motion_controller</exec_depend>
  <exec_depend>amr_bt_navigator</exec_depend>
  <exec_depend>amr_rviz_plugins</exec_depend>
  <exec_depend>amr_bringup</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
