/amr/mqtt_bridge:
  ros__parameters:
    broker:
      host: "127.0.0.1"
      port: 1883
      client_id: "amr_mqtt_bridge"
      keep_alive_sec: 20
      clean_session: true
      username: ""
      password: ""
    mqtt:
      root: "amr"
      qos:
        telemetry: 0
        command: 1
        service: 1
      topics:
        telemetry:
          robot_pose: "amr/telemetry/robot_pose"
          global_path: "amr/telemetry/global_path"
          local_path: "amr/telemetry/local_path"
          map: "amr/telemetry/map"
          global_costmap: "amr/telemetry/global_costmap"
          local_costmap: "amr/telemetry/local_costmap"
          motion_status: "amr/telemetry/motion_status"
          obstacle_report: "amr/telemetry/obstacle_report"
        command:
          robot_cmd_vel: "amr/robot/turtlebot3/command/cmd_vel"
          navigate_to_pose: "amr/command/navigate_to_pose"
          set_initial_pose: "amr/command/set_initial_pose"
        robot:
          telemetry:
            scan: "amr/robot/turtlebot3/telemetry/scan"
            odom: "amr/robot/turtlebot3/telemetry/odom"
            imu: "amr/robot/turtlebot3/telemetry/imu"
            tf: "amr/robot/turtlebot3/telemetry/tf"
            tf_static: "amr/robot/turtlebot3/telemetry/tf_static"
            joint_states: "amr/robot/turtlebot3/telemetry/joint_states"
        feedback:
          navigate_to_pose: "amr/feedback/navigate_to_pose"
        response:
          set_initial_pose: "amr/response/set_initial_pose"
          navigate_to_pose: "amr/response/navigate_to_pose"
          plan_segment: "amr/response/plan_segment"
          plan_route: "amr/response/plan_route"
        request:
          plan_segment: "amr/request/plan_segment"
          plan_route: "amr/request/plan_route"
    ros:
      topics:
        robot_pose: "/amr/localization/pose"
        global_path: "/amr/planner/global"
        local_path: "/amr/planner/local"
        map: "/amr/map/data"
        global_costmap: "/amr/costmap/global"
        local_costmap: "/amr/costmap/local"
        motion_status: "/amr/motion/status"
        obstacle_report: "/amr/obstacle/report"
        velocity: "/cmd_vel"
        initial_pose: "/amr/localization/initial_pose"
        robot:
          scan: "/scan"
          odom: "/odom"
          imu: "/imu"
          tf: "/tf"
          tf_static: "/tf_static"
          joint_states: "/joint_states"
      services:
        plan_segment: "/amr/global_planner/plan_segment"
        plan_route: "/amr/global_planner/plan_route"
      actions:
        navigate_to_pose: "/amr/navigator/navigate_to_pose"
