<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>amr_bringup</name>
  <version>0.1.0</version>
  <description>Launch and runtime assets for the ROS AMR navigation stack.</description>
  <maintainer email="reidlo4215@gmail.com">reidlo</maintainer>
  <license>TODO: License declaration</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>lifecycle_msgs</exec_depend>
  <exec_depend>turtlebot3_bringup</exec_depend>
  <exec_depend>amr_map_server</exec_depend>
  <exec_depend>amr_slam_mapper</exec_depend>
  <exec_depend>amr_localization</exec_depend>
  <exec_depend>amr_costmap_server</exec_depend>
  <exec_depend>amr_global_planner</exec_depend>
  <exec_depend>amr_local_planner</exec_depend>
  <exec_depend>amr_motion_controller</exec_depend>
  <exec_depend>amr_recovery_server</exec_depend>
  <exec_depend>amr_bt_navigator</exec_depend>
  <exec_depend>amr_lifecycle_manager</exec_depend>
  <exec_depend>amr_mqtt_bridge</exec_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
